//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Srs.Mobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Srs.Mobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected aisle has been scanned already. Do you want to perform a new scan? If you continue the previous records will be erased..
        /// </summary>
        internal static string Aisle_Already_Scanned {
            get {
                return ResourceManager.GetString("Aisle_Already_Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to complete the stock take?.
        /// </summary>
        internal static string Complete_Stock_Take {
            get {
                return ResourceManager.GetString("Complete_Stock_Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config file does not exist.
        /// </summary>
        internal static string Config_Not_Exists {
            get {
                return ResourceManager.GetString("Config_Not_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download the aisle information. Please check the connection and try again.
        /// </summary>
        internal static string Download_Aisle_Error {
            get {
                return ResourceManager.GetString("Download_Aisle_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit without completing the stock take?.
        /// </summary>
        internal static string Exit_Stock_Take {
            get {
                return ResourceManager.GetString("Exit_Stock_Take", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Trigger.
        /// </summary>
        internal static string Failed_Trigger {
            get {
                return ResourceManager.GetString("Failed_Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected record?.
        /// </summary>
        internal static string Incomplete_Remove_Selected {
            get {
                return ResourceManager.GetString("Incomplete_Remove_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Reader not initialized.
        /// </summary>
        internal static string Reader_Not_Initialized {
            get {
                return ResourceManager.GetString("Reader_Not_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an aisle to scan.
        /// </summary>
        internal static string Select_Aisle {
            get {
                return ResourceManager.GetString("Select_Aisle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRS Mobile.
        /// </summary>
        internal static string Srs_Title {
            get {
                return ResourceManager.GetString("Srs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock take completed but an database error occured.
        /// </summary>
        internal static string Stock_Take_Completed_Db_Error {
            get {
                return ResourceManager.GetString("Stock_Take_Completed_Db_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock-take completed sucessfully but couldn&apos;t upload data to the server.
        /// </summary>
        internal static string Stock_Take_Completed_Upload_Error {
            get {
                return ResourceManager.GetString("Stock_Take_Completed_Upload_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock take completed &amp; uploaded succesfully.
        /// </summary>
        internal static string Stock_Take_Sucessfull {
            get {
                return ResourceManager.GetString("Stock_Take_Sucessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to go back without completing the aisle scan?.
        /// </summary>
        internal static string Tag_Scan_Back {
            get {
                return ResourceManager.GetString("Tag_Scan_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to complete the aisle scan?.
        /// </summary>
        internal static string Tag_Scan_Complete {
            get {
                return ResourceManager.GetString("Tag_Scan_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove all the records?.
        /// </summary>
        internal static string Uncompleted_RemoveAll {
            get {
                return ResourceManager.GetString("Uncompleted_RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed. Please view history for unsucessfull uploads .
        /// </summary>
        internal static string Upload_Retried {
            get {
                return ResourceManager.GetString("Upload_Retried", resourceCulture);
            }
        }
    }
}
