//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4971
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.4971.
// 
namespace Srs.Mobile.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="serverBinding", Namespace="urn:server")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(StockItems))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Aisles))]
    public partial class server : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public server() {
            this.Url = "http://sachith.sexyi.am/srs/ws/srswebservice.php";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:server#loginServer", RequestNamespace="urn:server", ResponseNamespace="urn:server")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int login(string username, string password) {
            object[] results = this.Invoke("login", new object[] {
                        username,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(string username, string password, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login", new object[] {
                        username,
                        password}, callback, asyncState);
        }
        
        /// <remarks/>
        public int Endlogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:server#productAllServer", RequestNamespace="urn:server", ResponseNamespace="urn:server")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public Aisles[] GetAllAisles() {
            object[] results = this.Invoke("GetAllAisles", new object[0]);
            return ((Aisles[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetAllAisles(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetAllAisles", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public Aisles[] EndGetAllAisles(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Aisles[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:server#insertStockServer", RequestNamespace="urn:server", ResponseNamespace="urn:server")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public int InsertStockCount(StockItems[] StockItems, Stock Stock) {
            object[] results = this.Invoke("InsertStockCount", new object[] {
                        StockItems,
                        Stock});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginInsertStockCount(StockItems[] StockItems, Stock Stock, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("InsertStockCount", new object[] {
                        StockItems,
                        Stock}, callback, asyncState);
        }
        
        /// <remarks/>
        public int EndInsertStockCount(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:server")]
    public partial class Aisles {
        
        private int aisle_idField;
        
        private string aisle_descriptionField;
        
        private string aisle_numberField;
        
        /// <remarks/>
        public int aisle_id {
            get {
                return this.aisle_idField;
            }
            set {
                this.aisle_idField = value;
            }
        }
        
        /// <remarks/>
        public string aisle_description {
            get {
                return this.aisle_descriptionField;
            }
            set {
                this.aisle_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string aisle_number {
            get {
                return this.aisle_numberField;
            }
            set {
                this.aisle_numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:server")]
    public partial class Stock {
        
        private int stocktake_idField;
        
        private string time_startField;
        
        private string time_finishedField;
        
        private string user_nameField;
        
        private int upload_statusField;
        
        /// <remarks/>
        public int stocktake_id {
            get {
                return this.stocktake_idField;
            }
            set {
                this.stocktake_idField = value;
            }
        }
        
        /// <remarks/>
        public string time_start {
            get {
                return this.time_startField;
            }
            set {
                this.time_startField = value;
            }
        }
        
        /// <remarks/>
        public string time_finished {
            get {
                return this.time_finishedField;
            }
            set {
                this.time_finishedField = value;
            }
        }
        
        /// <remarks/>
        public string user_name {
            get {
                return this.user_nameField;
            }
            set {
                this.user_nameField = value;
            }
        }
        
        /// <remarks/>
        public int upload_status {
            get {
                return this.upload_statusField;
            }
            set {
                this.upload_statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:server")]
    public partial class StockItems {
        
        private int stocktake_idField;
        
        private int aisle_idField;
        
        private string aisle_numberField;
        
        private string tag_idField;
        
        /// <remarks/>
        public int stocktake_id {
            get {
                return this.stocktake_idField;
            }
            set {
                this.stocktake_idField = value;
            }
        }
        
        /// <remarks/>
        public int aisle_id {
            get {
                return this.aisle_idField;
            }
            set {
                this.aisle_idField = value;
            }
        }
        
        /// <remarks/>
        public string aisle_number {
            get {
                return this.aisle_numberField;
            }
            set {
                this.aisle_numberField = value;
            }
        }
        
        /// <remarks/>
        public string tag_id {
            get {
                return this.tag_idField;
            }
            set {
                this.tag_idField = value;
            }
        }
    }
}
